# Generated by Django 4.0.6 on 2022-07-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_criacao_modelbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='course.course')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
