# Generated by Django 4.0.6 on 2022-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_creating_employee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
